-- | This module contains reexports of all the DOM elements.
-- This module has been automatically generated by running `spago run -p codegen`.
-- Any changes may be overwritten.
module Deku.DOM
  ( module Deku.Control
  , module Deku.Attribute
  , class TagToDeku
  , html
  , html_
  , html__
  , head
  , head_
  , head__
  , title
  , title_
  , title__
  , base
  , base_
  , base__
  , link
  , link_
  , link__
  , meta
  , meta_
  , meta__
  , style
  , style_
  , style__
  , body
  , body_
  , body__
  , article
  , article_
  , article__
  , section
  , section_
  , section__
  , nav
  , nav_
  , nav__
  , aside
  , aside_
  , aside__
  , h1
  , h1_
  , h1__
  , h2
  , h2_
  , h2__
  , h3
  , h3_
  , h3__
  , h4
  , h4_
  , h4__
  , h5
  , h5_
  , h5__
  , h6
  , h6_
  , h6__
  , hgroup
  , hgroup_
  , hgroup__
  , header
  , header_
  , header__
  , footer
  , footer_
  , footer__
  , address
  , address_
  , address__
  , p
  , p_
  , p__
  , hr
  , hr_
  , hr__
  , pre
  , pre_
  , pre__
  , blockquote
  , blockquote_
  , blockquote__
  , ol
  , ol_
  , ol__
  , ul
  , ul_
  , ul__
  , menu
  , menu_
  , menu__
  , li
  , li_
  , li__
  , dl
  , dl_
  , dl__
  , dt
  , dt_
  , dt__
  , dd
  , dd_
  , dd__
  , figure
  , figure_
  , figure__
  , figcaption
  , figcaption_
  , figcaption__
  , main
  , main_
  , main__
  , search
  , search_
  , search__
  , div
  , div_
  , div__
  , a
  , a_
  , a__
  , em
  , em_
  , em__
  , strong
  , strong_
  , strong__
  , small
  , small_
  , small__
  , s
  , s_
  , s__
  , cite
  , cite_
  , cite__
  , q
  , q_
  , q__
  , dfn
  , dfn_
  , dfn__
  , abbr
  , abbr_
  , abbr__
  , ruby
  , ruby_
  , ruby__
  , rt
  , rt_
  , rt__
  , rp
  , rp_
  , rp__
  , xdata
  , xdata_
  , xdata__
  , time
  , time_
  , time__
  , code
  , code_
  , code__
  , var
  , var_
  , var__
  , samp
  , samp_
  , samp__
  , kbd
  , kbd_
  , kbd__
  , sub
  , sub_
  , sub__
  , sup
  , sup_
  , sup__
  , i
  , i_
  , i__
  , b
  , b_
  , b__
  , u
  , u_
  , u__
  , mark
  , mark_
  , mark__
  , bdi
  , bdi_
  , bdi__
  , bdo
  , bdo_
  , bdo__
  , span
  , span_
  , span__
  , br
  , br_
  , br__
  , wbr
  , wbr_
  , wbr__
  , ins
  , ins_
  , ins__
  , del
  , del_
  , del__
  , picture
  , picture_
  , picture__
  , source
  , source_
  , source__
  , img
  , img_
  , img__
  , iframe
  , iframe_
  , iframe__
  , embed
  , embed_
  , embed__
  , object
  , object_
  , object__
  , video
  , video_
  , video__
  , audio
  , audio_
  , audio__
  , track
  , track_
  , track__
  , map
  , map_
  , map__
  , area
  , area_
  , area__
  , table
  , table_
  , table__
  , caption
  , caption_
  , caption__
  , colgroup
  , colgroup_
  , colgroup__
  , col
  , col_
  , col__
  , tbody
  , tbody_
  , tbody__
  , thead
  , thead_
  , thead__
  , tfoot
  , tfoot_
  , tfoot__
  , tr
  , tr_
  , tr__
  , td
  , td_
  , td__
  , th
  , th_
  , th__
  , form
  , form_
  , form__
  , label
  , label_
  , label__
  , input
  , input_
  , input__
  , button
  , button_
  , button__
  , select
  , select_
  , select__
  , datalist
  , datalist_
  , datalist__
  , optgroup
  , optgroup_
  , optgroup__
  , option
  , option_
  , option__
  , textarea
  , textarea_
  , textarea__
  , output
  , output_
  , output__
  , progress
  , progress_
  , progress__
  , meter
  , meter_
  , meter__
  , fieldset
  , fieldset_
  , fieldset__
  , legend
  , legend_
  , legend__
  , details
  , details_
  , details__
  , summary
  , summary_
  , summary__
  , dialog
  , dialog_
  , dialog__
  , script
  , script_
  , script__
  , noscript
  , noscript_
  , noscript__
  , template
  , template_
  , template__
  , slot
  , slot_
  , slot__
  , canvas
  , canvas_
  , canvas__
  , applet
  , applet_
  , applet__
  , acronym
  , acronym_
  , acronym__
  , bgsound
  , bgsound_
  , bgsound__
  , dir
  , dir_
  , dir__
  , frame
  , frame_
  , frame__
  , frameset
  , frameset_
  , frameset__
  , noframes
  , noframes_
  , noframes__
  , isindex
  , isindex_
  , isindex__
  , keygen
  , keygen_
  , keygen__
  , listing
  , listing_
  , listing__
  , menuitem
  , menuitem_
  , menuitem__
  , nextid
  , nextid_
  , nextid__
  , noembed
  , noembed_
  , noembed__
  , param
  , param_
  , param__
  , plaintext
  , plaintext_
  , plaintext__
  , rb
  , rb_
  , rb__
  , rtc
  , rtc_
  , rtc__
  , strike
  , strike_
  , strike__
  , xmp
  , xmp_
  , xmp__
  , basefont
  , basefont_
  , basefont__
  , big
  , big_
  , big__
  , blink
  , blink_
  , blink__
  , center
  , center_
  , center__
  , font
  , font_
  , font__
  , marquee
  , marquee_
  , marquee__
  , multicol
  , multicol_
  , multicol__
  , nobr
  , nobr_
  , nobr__
  , spacer
  , spacer_
  , spacer__
  , tt
  , tt_
  , tt__
  , ARIAMixin
  , HTMLElement
  , HTMLUnknownElement
  , HTMLOrSVGElement
  , HTMLHtmlElement
  , HTMLHeadElement
  , HTMLTitleElement
  , HTMLBaseElement
  , HTMLLinkElement
  , HTMLMetaElement
  , HTMLStyleElement
  , HTMLBodyElement
  , HTMLHeadingElement
  , HTMLParagraphElement
  , HTMLHRElement
  , HTMLPreElement
  , HTMLQuoteElement
  , HTMLOListElement
  , HTMLUListElement
  , HTMLMenuElement
  , HTMLLIElement
  , HTMLDListElement
  , HTMLDivElement
  , HTMLAnchorElement
  , HTMLDataElement
  , HTMLTimeElement
  , HTMLSpanElement
  , HTMLBRElement
  , HTMLHyperlinkElementUtils
  , HTMLModElement
  , HTMLPictureElement
  , HTMLSourceElement
  , HTMLImageElement
  , HTMLIFrameElement
  , HTMLEmbedElement
  , HTMLObjectElement
  , HTMLVideoElement
  , HTMLAudioElement
  , HTMLTrackElement
  , HTMLMediaElement
  , HTMLMapElement
  , HTMLAreaElement
  , HTMLTableElement
  , HTMLTableCaptionElement
  , HTMLTableColElement
  , HTMLTableSectionElement
  , HTMLTableRowElement
  , HTMLTableCellElement
  , HTMLFormElement
  , HTMLLabelElement
  , HTMLInputElement
  , HTMLButtonElement
  , HTMLSelectElement
  , HTMLDataListElement
  , HTMLOptGroupElement
  , HTMLOptionElement
  , HTMLTextAreaElement
  , HTMLOutputElement
  , HTMLProgressElement
  , HTMLMeterElement
  , HTMLFieldSetElement
  , HTMLLegendElement
  , HTMLDetailsElement
  , HTMLDialogElement
  , HTMLScriptElement
  , HTMLTemplateElement
  , HTMLSlotElement
  , HTMLCanvasElement
  , ElementContentEditable
  , PopoverInvokerElement
  , GlobalEventHandlers
  , WindowEventHandlers
  , HTMLMarqueeElement
  , HTMLFrameSetElement
  , HTMLFrameElement
  , HTMLDirectoryElement
  , HTMLFontElement
  , HTMLParamElement
  , EventTarget
  , ParentNode
  , NonDocumentTypeChildNode
  , ChildNode
  , Slottable
  , Node
  , Element
  ) where

import Deku.Control (text, text_) as Deku.Control
import FRP.Poll as FRP.Poll
import Data.Maybe (Maybe(..))
import Deku.Attribute (Attribute) as Deku.Attribute
import Deku.Control (elementify2)
import Deku.Control as DC
import Deku.Core (Nut)
import Type.Proxy (Proxy)
import Web.Event.Internal.Types as Web.Event.Internal.Types
import Web.PointerEvent.PointerEvent as Web.PointerEvent.PointerEvent
import Web.HTML.Event.DragEvent as Web.HTML.Event.DragEvent
import Web.UIEvent.KeyboardEvent as Web.UIEvent.KeyboardEvent
import Web.UIEvent.FocusEvent as Web.UIEvent.FocusEvent
import Web.UIEvent.UIEvent as Web.UIEvent.UIEvent
import Web.UIEvent.MouseEvent as Web.UIEvent.MouseEvent
import Web.UIEvent.CompositionEvent as Web.UIEvent.CompositionEvent
import Web.TouchEvent.TouchEvent as Web.TouchEvent.TouchEvent

class TagToDeku (tag :: Symbol) (interface :: Row Type) | tag -> interface
type ARIAMixin (r :: Row Type) =
  ( __tag :: Proxy "ARIAMixin"
  , ariaValuetext :: String
  , ariaValuenow :: String
  , ariaValuemin :: String
  , ariaValuemax :: String
  , ariaSort :: String
  , ariaSetsize :: String
  , ariaSelected :: String
  , ariaRowspan :: String
  , ariaRowindextext :: String
  , ariaRowindex :: String
  , ariaRowcount :: String
  , ariaRoledescription :: String
  , ariaRequired :: String
  , ariaReadonly :: String
  , ariaPressed :: String
  , ariaPosinset :: String
  , ariaPlaceholder :: String
  , ariaOwns :: String
  , ariaOrientation :: String
  , ariaMultiselectable :: String
  , ariaMultiline :: String
  , ariaModal :: String
  , ariaLive :: String
  , ariaLevel :: String
  , ariaLabelledby :: String
  , ariaLabel :: String
  , ariaKeyshortcuts :: String
  , ariaInvalid :: String
  , ariaHidden :: String
  , ariaHaspopup :: String
  , ariaFlowto :: String
  , ariaExpanded :: String
  , ariaErrormessage :: String
  , ariaDisabled :: String
  , ariaDetails :: String
  , ariaDescription :: String
  , ariaDescribedby :: String
  , ariaCurrent :: String
  , ariaControls :: String
  , ariaColspan :: String
  , ariaColindextext :: String
  , ariaColindex :: String
  , ariaColcount :: String
  , ariaChecked :: String
  , ariaBusy :: String
  , ariaAutocomplete :: String
  , ariaAtomic :: String
  , ariaActivedescendant :: String
  , role :: String
  | r
  )

type HTMLElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLElement"
  , popovertargetaction :: String
  , popovertarget :: String
  , popover :: String
  , draggable :: String
  , enterkeyhint :: String
  , inputmode :: String
  , autocapitalize :: String
  , spellcheck :: String
  , contenteditable :: String
  , accesskey :: String
  , autofocus :: String
  , hidden :: String
  , itemprop :: String
  , itemref :: String
  , itemid :: String
  , itemtype :: String
  , itemscope :: String
  , is :: String
  , title :: String
  , style :: String
  , dir :: String
  , translate :: String
  , lang :: String
  , load :: Web.Event.Internal.Types.Event
  , error :: Web.Event.Internal.Types.Event
  , beforetoggle :: Web.Event.Internal.Types.Event
  , beforematch :: Web.Event.Internal.Types.Event
  | HTMLOrSVGElement (ElementContentEditable (GlobalEventHandlers (Element r)))
  )

type HTMLUnknownElement (r :: Row Type) = (__tag :: Proxy "HTMLUnknownElement" | HTMLElement r)
type HTMLOrSVGElement (r :: Row Type) =
  (__tag :: Proxy "HTMLOrSVGElement", tabindex :: String, nonce :: String | r)

type HTMLHtmlElement (r :: Row Type) =
  (__tag :: Proxy "HTMLHtmlElement", version :: String, manifest :: String | HTMLElement r)

type HTMLHeadElement (r :: Row Type) =
  (__tag :: Proxy "HTMLHeadElement", profile :: String | HTMLElement r)

type HTMLTitleElement (r :: Row Type) = (__tag :: Proxy "HTMLTitleElement" | HTMLElement r)
type HTMLBaseElement (r :: Row Type) =
  (__tag :: Proxy "HTMLBaseElement", target :: String, href :: String | HTMLElement r)

type HTMLLinkElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLLinkElement"
  , target :: String
  , urn :: String
  , rev :: String
  , methods :: String
  , charset :: String
  , fetchpriority :: String
  , disabled :: String
  , color :: String
  , blocking :: String
  , as :: String
  , sizes :: String
  , imagesizes :: String
  , imagesrcset :: String
  , title :: String
  , referrerpolicy :: String
  , xtype :: String
  , hreflang :: String
  , integrity :: String
  , media :: String
  , crossorigin :: String
  , rel :: String
  , href :: String
  | HTMLElement r
  )

type HTMLMetaElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLMetaElement"
  , scheme :: String
  , httpEquiv :: String
  , media :: String
  , name :: String
  , content :: String
  , charset :: String
  | HTMLElement r
  )

type HTMLStyleElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLStyleElement"
  , xtype :: String
  , title :: String
  , blocking :: String
  , media :: String
  | HTMLElement r
  )

type HTMLBodyElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLBodyElement"
  , vlink :: String
  , topmargin :: String
  , text :: String
  , rightmargin :: String
  , marginwidth :: String
  , marginheight :: String
  , link :: String
  , leftmargin :: String
  , bottommargin :: String
  , bgcolor :: String
  , alink :: String
  | WindowEventHandlers (HTMLElement r)
  )

type HTMLHeadingElement (r :: Row Type) =
  (__tag :: Proxy "HTMLHeadingElement", align :: String | HTMLElement r)

type HTMLParagraphElement (r :: Row Type) =
  (__tag :: Proxy "HTMLParagraphElement", align :: String | HTMLElement r)

type HTMLHRElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLHRElement"
  , width :: String
  , size :: String
  , noshade :: String
  , color :: String
  , align :: String
  | HTMLElement r
  )

type HTMLPreElement (r :: Row Type) =
  (__tag :: Proxy "HTMLPreElement", width :: String | HTMLElement r)

type HTMLQuoteElement (r :: Row Type) =
  (__tag :: Proxy "HTMLQuoteElement", cite :: String | HTMLElement r)

type HTMLOListElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLOListElement"
  , compact :: String
  , xtype :: String
  , start :: String
  , reversed :: String
  | HTMLElement r
  )

type HTMLUListElement (r :: Row Type) =
  (__tag :: Proxy "HTMLUListElement", xtype :: String, compact :: String | HTMLElement r)

type HTMLMenuElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLMenuElement"
  , compact :: String
  , label :: String
  , xtype :: String
  | HTMLElement r
  )

type HTMLLIElement (r :: Row Type) =
  (__tag :: Proxy "HTMLLIElement", xtype :: String, value :: String | HTMLElement r)

type HTMLDListElement (r :: Row Type) =
  (__tag :: Proxy "HTMLDListElement", compact :: String | HTMLElement r)

type HTMLDivElement (r :: Row Type) =
  (__tag :: Proxy "HTMLDivElement", align :: String | HTMLElement r)

type HTMLAnchorElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLAnchorElement"
  , urn :: String
  , rev :: String
  , name :: String
  , methods :: String
  , shape :: String
  , coords :: String
  , charset :: String
  , referrerpolicy :: String
  , xtype :: String
  , hreflang :: String
  , rel :: String
  , ping :: String
  , download :: String
  , target :: String
  , href :: String
  | HTMLHyperlinkElementUtils (HTMLElement r)
  )

type HTMLDataElement (r :: Row Type) =
  (__tag :: Proxy "HTMLDataElement", value :: String | HTMLElement r)

type HTMLTimeElement (r :: Row Type) =
  (__tag :: Proxy "HTMLTimeElement", datetime :: String | HTMLElement r)

type HTMLSpanElement (r :: Row Type) = (__tag :: Proxy "HTMLSpanElement" | HTMLElement r)
type HTMLBRElement (r :: Row Type) =
  (__tag :: Proxy "HTMLBRElement", clear :: String | HTMLElement r)

type HTMLHyperlinkElementUtils (r :: Row Type) = (__tag :: Proxy "HTMLHyperlinkElementUtils" | r)
type HTMLModElement (r :: Row Type) =
  (__tag :: Proxy "HTMLModElement", datetime :: String, cite :: String | HTMLElement r)

type HTMLPictureElement (r :: Row Type) = (__tag :: Proxy "HTMLPictureElement" | HTMLElement r)
type HTMLSourceElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLSourceElement"
  , height :: String
  , width :: String
  , src :: String
  , sizes :: String
  , srcset :: String
  , media :: String
  , xtype :: String
  , error :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLImageElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLImageElement"
  , vspace :: String
  , hspace :: String
  , border :: String
  , align :: String
  , lowsrc :: String
  , longdesc :: String
  , name :: String
  , height :: String
  , width :: String
  , usemap :: String
  , ismap :: String
  , loading :: String
  , fetchpriority :: String
  , decoding :: String
  , referrerpolicy :: String
  , crossorigin :: String
  , sizes :: String
  , alt :: String
  , srcset :: String
  , src :: String
  | HTMLElement r
  )

type HTMLIFrameElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLIFrameElement"
  , vspace :: String
  , scrolling :: String
  , marginwidth :: String
  , marginheight :: String
  , hspace :: String
  , framespacing :: String
  , frameborder :: String
  , allowtransparency :: String
  , align :: String
  , longdesc :: String
  , height :: String
  , width :: String
  , loading :: String
  , referrerpolicy :: String
  , allowfullscreen :: String
  , allow :: String
  , sandbox :: String
  , name :: String
  , srcdoc :: String
  , src :: String
  | HTMLElement r
  )

type HTMLEmbedElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLEmbedElement"
  , vspace :: String
  , hspace :: String
  , align :: String
  , name :: String
  , height :: String
  , width :: String
  , xtype :: String
  , src :: String
  | HTMLElement r
  )

type HTMLObjectElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLObjectElement"
  , vspace :: String
  , hspace :: String
  , border :: String
  , align :: String
  , typemustmatch :: String
  , standby :: String
  , declare :: String
  , codetype :: String
  , codebase :: String
  , code :: String
  , classid :: String
  , archive :: String
  , usemap :: String
  , autocomplete :: String
  , disabled :: String
  , form :: String
  , height :: String
  , width :: String
  , name :: String
  , xtype :: String
  , xdata :: String
  | HTMLElement r
  )

type HTMLVideoElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLVideoElement"
  , height :: String
  , width :: String
  , muted :: String
  , controls :: String
  , autoplay :: String
  , loop :: String
  , preload :: String
  , crossorigin :: String
  , src :: String
  , playsinline :: String
  , poster :: String
  | HTMLMediaElement r
  )

type HTMLAudioElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLAudioElement"
  , muted :: String
  , controls :: String
  , autoplay :: String
  , loop :: String
  , preload :: String
  , crossorigin :: String
  , src :: String
  | HTMLMediaElement r
  )

type HTMLTrackElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLTrackElement"
  , default :: String
  , label :: String
  , srclang :: String
  , src :: String
  , kind :: String
  , load :: Web.Event.Internal.Types.Event
  , error :: Web.Event.Internal.Types.Event
  , cuechange :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLMediaElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLMediaElement"
  , volumechange :: Web.Event.Internal.Types.Event
  , resize :: Web.Event.Internal.Types.Event
  , ratechange :: Web.Event.Internal.Types.Event
  , pause :: Web.Event.Internal.Types.Event
  , play :: Web.Event.Internal.Types.Event
  , timeupdate :: Web.Event.Internal.Types.Event
  , durationchange :: Web.Event.Internal.Types.Event
  , ended :: Web.Event.Internal.Types.Event
  , seeked :: Web.Event.Internal.Types.Event
  , seeking :: Web.Event.Internal.Types.Event
  , waiting :: Web.Event.Internal.Types.Event
  , playing :: Web.Event.Internal.Types.Event
  , canplaythrough :: Web.Event.Internal.Types.Event
  , canplay :: Web.Event.Internal.Types.Event
  , loadeddata :: Web.Event.Internal.Types.Event
  , loadedmetadata :: Web.Event.Internal.Types.Event
  , stalled :: Web.Event.Internal.Types.Event
  , emptied :: Web.Event.Internal.Types.Event
  , error :: Web.Event.Internal.Types.Event
  , abort :: Web.Event.Internal.Types.Event
  , suspend :: Web.Event.Internal.Types.Event
  , progress :: Web.Event.Internal.Types.Event
  , loadstart :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLMapElement (r :: Row Type) =
  (__tag :: Proxy "HTMLMapElement", name :: String | HTMLElement r)

type HTMLAreaElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLAreaElement"
  , nohref :: String
  , xtype :: String
  , hreflang :: String
  , coords :: String
  , shape :: String
  , alt :: String
  , referrerpolicy :: String
  , rel :: String
  , ping :: String
  , download :: String
  , target :: String
  , href :: String
  | HTMLHyperlinkElementUtils (HTMLElement r)
  )

type HTMLTableElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLTableElement"
  , width :: String
  , rules :: String
  , height :: String
  , frame :: String
  , cellspacing :: String
  , cellpadding :: String
  , bordercolor :: String
  , border :: String
  , bgcolor :: String
  , align :: String
  , summary :: String
  , datapagesize :: String
  | HTMLElement r
  )

type HTMLTableCaptionElement (r :: Row Type) =
  (__tag :: Proxy "HTMLTableCaptionElement", align :: String | HTMLElement r)

type HTMLTableColElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLTableColElement"
  , width :: String
  , valign :: String
  , charoff :: String
  , char :: String
  , align :: String
  , span :: String
  | HTMLElement r
  )

type HTMLTableSectionElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLTableSectionElement"
  , valign :: String
  , height :: String
  , charoff :: String
  , char :: String
  , align :: String
  | HTMLElement r
  )

type HTMLTableRowElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLTableRowElement"
  , valign :: String
  , height :: String
  , charoff :: String
  , char :: String
  , bgcolor :: String
  , align :: String
  | HTMLElement r
  )

type HTMLTableCellElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLTableCellElement"
  , width :: String
  , valign :: String
  , nowrap :: String
  , height :: String
  , charoff :: String
  , char :: String
  , bgcolor :: String
  , align :: String
  , scope :: String
  , axis :: String
  , abbr :: String
  , headers :: String
  , rowspan :: String
  , colspan :: String
  | HTMLElement r
  )

type HTMLFormElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLFormElement"
  , accept :: String
  , formnovalidate :: String
  , novalidate :: String
  , formtarget :: String
  , target :: String
  , formenctype :: String
  , enctype :: String
  , formmethod :: String
  , method :: String
  , formaction :: String
  , action :: String
  , rel :: String
  , autocomplete :: String
  , name :: String
  , acceptCharset :: String
  , submit :: Web.Event.Internal.Types.Event
  , reset :: Web.Event.Internal.Types.Event
  , formdata :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLLabelElement (r :: Row Type) =
  (__tag :: Proxy "HTMLLabelElement", for :: String | HTMLElement r)

type HTMLInputElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLInputElement"
  , capture :: String
  , vspace :: String
  , hspace :: String
  , border :: String
  , align :: String
  , usemap :: String
  , ismap :: String
  , autocomplete :: String
  , disabled :: String
  , minlength :: String
  , maxlength :: String
  , dirname :: String
  , name :: String
  , form :: String
  , placeholder :: String
  , list :: String
  , step :: String
  , max :: String
  , min :: String
  , title :: String
  , pattern :: String
  , multiple :: String
  , required :: String
  , readonly :: String
  , size :: String
  , alt :: String
  , src :: String
  , accept :: String
  , checked :: String
  , value :: String
  , xtype :: String
  , select :: Web.Event.Internal.Types.Event
  , invalid :: Web.Event.Internal.Types.Event
  , change :: Web.Event.Internal.Types.Event
  , cancel :: Web.Event.Internal.Types.Event
  | PopoverInvokerElement (HTMLElement r)
  )

type HTMLButtonElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLButtonElement"
  , autocomplete :: String
  , formnovalidate :: String
  , novalidate :: String
  , formtarget :: String
  , target :: String
  , formenctype :: String
  , enctype :: String
  , formmethod :: String
  , method :: String
  , formaction :: String
  , action :: String
  , disabled :: String
  , name :: String
  , form :: String
  , value :: String
  , xtype :: String
  , invalid :: Web.Event.Internal.Types.Event
  | PopoverInvokerElement (HTMLElement r)
  )

type HTMLSelectElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLSelectElement"
  , autocomplete :: String
  , disabled :: String
  , name :: String
  , form :: String
  , required :: String
  , size :: String
  , multiple :: String
  , invalid :: Web.Event.Internal.Types.Event
  , change :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLDataListElement (r :: Row Type) = (__tag :: Proxy "HTMLDataListElement" | HTMLElement r)
type HTMLOptGroupElement (r :: Row Type) =
  (__tag :: Proxy "HTMLOptGroupElement", label :: String, disabled :: String | HTMLElement r)

type HTMLOptionElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLOptionElement"
  , name :: String
  , selected :: String
  , value :: String
  , label :: String
  , disabled :: String
  | HTMLElement r
  )

type HTMLTextAreaElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLTextAreaElement"
  , autocomplete :: String
  , disabled :: String
  , minlength :: String
  , maxlength :: String
  , dirname :: String
  , name :: String
  , form :: String
  , placeholder :: String
  , required :: String
  , wrap :: String
  , rows :: String
  , cols :: String
  , readonly :: String
  , select :: Web.Event.Internal.Types.Event
  , invalid :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLOutputElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLOutputElement"
  , autocomplete :: String
  , disabled :: String
  , name :: String
  , form :: String
  , for :: String
  | HTMLElement r
  )

type HTMLProgressElement (r :: Row Type) =
  (__tag :: Proxy "HTMLProgressElement", max :: String, value :: String | HTMLElement r)

type HTMLMeterElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLMeterElement"
  , optimum :: String
  , high :: String
  , low :: String
  , value :: String
  , max :: String
  , min :: String
  | HTMLElement r
  )

type HTMLFieldSetElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLFieldSetElement"
  , autocomplete :: String
  , disabled :: String
  , name :: String
  , form :: String
  | HTMLElement r
  )

type HTMLLegendElement (r :: Row Type) =
  (__tag :: Proxy "HTMLLegendElement", align :: String | HTMLElement r)

type HTMLDetailsElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLDetailsElement"
  , open :: String
  , toggle :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLDialogElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLDialogElement"
  , open :: String
  , close :: Web.Event.Internal.Types.Event
  , cancel :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type HTMLScriptElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLScriptElement"
  , for :: String
  , event :: String
  , language :: String
  , charset :: String
  , fetchpriority :: String
  , blocking :: String
  , referrerpolicy :: String
  , integrity :: String
  , crossorigin :: String
  , defer :: String
  , async :: String
  , nomodule :: String
  , src :: String
  , xtype :: String
  | HTMLElement r
  )

type HTMLTemplateElement (r :: Row Type) = (__tag :: Proxy "HTMLTemplateElement" | HTMLElement r)
type HTMLSlotElement (r :: Row Type) =
  (__tag :: Proxy "HTMLSlotElement", name :: String | HTMLElement r)

type HTMLCanvasElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLCanvasElement"
  , height :: String
  , width :: String
  , contextrestored :: Web.Event.Internal.Types.Event
  , contextlost :: Web.Event.Internal.Types.Event
  | HTMLElement r
  )

type ElementContentEditable (r :: Row Type) = (__tag :: Proxy "ElementContentEditable" | r)
type PopoverInvokerElement (r :: Row Type) = (__tag :: Proxy "PopoverInvokerElement" | r)
type GlobalEventHandlers (r :: Row Type) =
  ( __tag :: Proxy "GlobalEventHandlers"
  , transitioncancel :: Web.Event.Internal.Types.Event
  , transitionend :: Web.Event.Internal.Types.Event
  , transitionstart :: Web.Event.Internal.Types.Event
  , transitionrun :: Web.Event.Internal.Types.Event
  , animationcancel :: Web.Event.Internal.Types.Event
  , animationend :: Web.Event.Internal.Types.Event
  , animationiteration :: Web.Event.Internal.Types.Event
  , animationstart :: Web.Event.Internal.Types.Event
  , lostpointercapture :: Web.PointerEvent.PointerEvent.PointerEvent
  , gotpointercapture :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointerleave :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointerout :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointercancel :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointerup :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointerrawupdate :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointermove :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointerdown :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointerenter :: Web.PointerEvent.PointerEvent.PointerEvent
  , pointerover :: Web.PointerEvent.PointerEvent.PointerEvent
  , dragend :: Web.HTML.Event.DragEvent.DragEvent
  , drop :: Web.HTML.Event.DragEvent.DragEvent
  , dragover :: Web.HTML.Event.DragEvent.DragEvent
  , dragleave :: Web.HTML.Event.DragEvent.DragEvent
  , dragenter :: Web.HTML.Event.DragEvent.DragEvent
  , drag :: Web.HTML.Event.DragEvent.DragEvent
  , dragstart :: Web.HTML.Event.DragEvent.DragEvent
  | r
  )

type WindowEventHandlers (r :: Row Type) = (__tag :: Proxy "WindowEventHandlers" | r)
type HTMLMarqueeElement (r :: Row Type) =
  ( __tag :: Proxy "HTMLMarqueeElement"
  , loop :: String
  , truespeed :: String
  , direction :: String
  , behavior :: String
  | HTMLElement r
  )

type HTMLFrameSetElement (r :: Row Type) =
  (__tag :: Proxy "HTMLFrameSetElement" | WindowEventHandlers (HTMLElement r))

type HTMLFrameElement (r :: Row Type) = (__tag :: Proxy "HTMLFrameElement" | HTMLElement r)
type HTMLDirectoryElement (r :: Row Type) = (__tag :: Proxy "HTMLDirectoryElement" | HTMLElement r)
type HTMLFontElement (r :: Row Type) = (__tag :: Proxy "HTMLFontElement" | HTMLElement r)
type HTMLParamElement (r :: Row Type) = (__tag :: Proxy "HTMLParamElement" | HTMLElement r)
type EventTarget (r :: Row Type) = (__tag :: Proxy "EventTarget" | r)
type ParentNode (r :: Row Type) = (__tag :: Proxy "ParentNode" | r)
type NonDocumentTypeChildNode (r :: Row Type) = (__tag :: Proxy "NonDocumentTypeChildNode" | r)
type ChildNode (r :: Row Type) = (__tag :: Proxy "ChildNode" | r)
type Slottable (r :: Row Type) = (__tag :: Proxy "Slottable" | r)
type Node (r :: Row Type) = (__tag :: Proxy "Node" | EventTarget r)
type Element (r :: Row Type) =
  ( __tag :: Proxy "Element"
  , slot :: String
  , id :: String
  , klass :: String
  , keypress :: Web.UIEvent.KeyboardEvent.KeyboardEvent
  , domSubtreeModified :: Web.Event.Internal.Types.Event
  , domNodeRemovedFromDocument :: Web.Event.Internal.Types.Event
  , domNodeRemoved :: Web.Event.Internal.Types.Event
  , domNodeInsertedIntoDocument :: Web.Event.Internal.Types.Event
  , domNodeInserted :: Web.Event.Internal.Types.Event
  , domFocusOut :: Web.UIEvent.FocusEvent.FocusEvent
  , domFocusIn :: Web.UIEvent.FocusEvent.FocusEvent
  , domAttrModified :: Web.Event.Internal.Types.Event
  , domActivate :: Web.UIEvent.UIEvent.UIEvent
  , wheel :: Web.Event.Internal.Types.Event
  , unload :: Web.Event.Internal.Types.Event
  , select :: Web.Event.Internal.Types.Event
  , mouseup :: Web.UIEvent.MouseEvent.MouseEvent
  , mouseover :: Web.UIEvent.MouseEvent.MouseEvent
  , mouseout :: Web.UIEvent.MouseEvent.MouseEvent
  , mousemove :: Web.UIEvent.MouseEvent.MouseEvent
  , mouseleave :: Web.UIEvent.MouseEvent.MouseEvent
  , mouseenter :: Web.UIEvent.MouseEvent.MouseEvent
  , mousedown :: Web.UIEvent.MouseEvent.MouseEvent
  , load :: Web.Event.Internal.Types.Event
  , keyup :: Web.UIEvent.KeyboardEvent.KeyboardEvent
  , keydown :: Web.UIEvent.KeyboardEvent.KeyboardEvent
  , input :: Web.Event.Internal.Types.Event
  , focusout :: Web.UIEvent.FocusEvent.FocusEvent
  , focusin :: Web.UIEvent.FocusEvent.FocusEvent
  , focus :: Web.UIEvent.FocusEvent.FocusEvent
  , error :: Web.Event.Internal.Types.Event
  , dblclick :: Web.UIEvent.MouseEvent.MouseEvent
  , contextmenu :: Web.PointerEvent.PointerEvent.PointerEvent
  , compositionend :: Web.UIEvent.CompositionEvent.CompositionEvent
  , compositionupdate :: Web.UIEvent.CompositionEvent.CompositionEvent
  , compositionstart :: Web.UIEvent.CompositionEvent.CompositionEvent
  , click :: Web.PointerEvent.PointerEvent.PointerEvent
  , blur :: Web.UIEvent.FocusEvent.FocusEvent
  , beforeinput :: Web.Event.Internal.Types.Event
  , auxclick :: Web.PointerEvent.PointerEvent.PointerEvent
  , abort :: Web.Event.Internal.Types.Event
  , touchcancel :: Web.TouchEvent.TouchEvent.TouchEvent
  , touchmove :: Web.TouchEvent.TouchEvent.TouchEvent
  , touchend :: Web.TouchEvent.TouchEvent.TouchEvent
  , touchstart :: Web.TouchEvent.TouchEvent.TouchEvent
  | ARIAMixin (Slottable (ChildNode (NonDocumentTypeChildNode (ParentNode (Node r)))))
  )

instance TagToDeku "html" (HTMLHtmlElement ())

html :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHtmlElement ()))) -> Array Nut -> Nut
html = elementify2 Nothing "html"

html_ :: Array Nut -> Nut
html_ = html []

html__ :: String -> Nut
html__ t = html [] [ DC.text_ t ]

instance TagToDeku "head" (HTMLHeadElement ())

head :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHeadElement ()))) -> Array Nut -> Nut
head = elementify2 Nothing "head"

head_ :: Array Nut -> Nut
head_ = head []

head__ :: String -> Nut
head__ t = head [] [ DC.text_ t ]

instance TagToDeku "title" (HTMLTitleElement ())

title :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTitleElement ()))) -> Array Nut -> Nut
title = elementify2 Nothing "title"

title_ :: Array Nut -> Nut
title_ = title []

title__ :: String -> Nut
title__ t = title [] [ DC.text_ t ]

instance TagToDeku "base" (HTMLBaseElement ())

base :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLBaseElement ()))) -> Array Nut -> Nut
base = elementify2 Nothing "base"

base_ :: Array Nut -> Nut
base_ = base []

base__ :: String -> Nut
base__ t = base [] [ DC.text_ t ]

instance TagToDeku "link" (HTMLLinkElement ())

link :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLLinkElement ()))) -> Array Nut -> Nut
link = elementify2 Nothing "link"

link_ :: Array Nut -> Nut
link_ = link []

link__ :: String -> Nut
link__ t = link [] [ DC.text_ t ]

instance TagToDeku "meta" (HTMLMetaElement ())

meta :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLMetaElement ()))) -> Array Nut -> Nut
meta = elementify2 Nothing "meta"

meta_ :: Array Nut -> Nut
meta_ = meta []

meta__ :: String -> Nut
meta__ t = meta [] [ DC.text_ t ]

instance TagToDeku "style" (HTMLStyleElement ())

style :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLStyleElement ()))) -> Array Nut -> Nut
style = elementify2 Nothing "style"

style_ :: Array Nut -> Nut
style_ = style []

style__ :: String -> Nut
style__ t = style [] [ DC.text_ t ]

instance TagToDeku "body" (HTMLBodyElement ())

body :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLBodyElement ()))) -> Array Nut -> Nut
body = elementify2 Nothing "body"

body_ :: Array Nut -> Nut
body_ = body []

body__ :: String -> Nut
body__ t = body [] [ DC.text_ t ]

instance TagToDeku "article" (HTMLElement ())

article :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
article = elementify2 Nothing "article"

article_ :: Array Nut -> Nut
article_ = article []

article__ :: String -> Nut
article__ t = article [] [ DC.text_ t ]

instance TagToDeku "section" (HTMLElement ())

section :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
section = elementify2 Nothing "section"

section_ :: Array Nut -> Nut
section_ = section []

section__ :: String -> Nut
section__ t = section [] [ DC.text_ t ]

instance TagToDeku "nav" (HTMLElement ())

nav :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
nav = elementify2 Nothing "nav"

nav_ :: Array Nut -> Nut
nav_ = nav []

nav__ :: String -> Nut
nav__ t = nav [] [ DC.text_ t ]

instance TagToDeku "aside" (HTMLElement ())

aside :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
aside = elementify2 Nothing "aside"

aside_ :: Array Nut -> Nut
aside_ = aside []

aside__ :: String -> Nut
aside__ t = aside [] [ DC.text_ t ]

instance TagToDeku "h1" (HTMLHeadingElement ())

h1 :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHeadingElement ()))) -> Array Nut -> Nut
h1 = elementify2 Nothing "h1"

h1_ :: Array Nut -> Nut
h1_ = h1 []

h1__ :: String -> Nut
h1__ t = h1 [] [ DC.text_ t ]

instance TagToDeku "h2" (HTMLHeadingElement ())

h2 :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHeadingElement ()))) -> Array Nut -> Nut
h2 = elementify2 Nothing "h2"

h2_ :: Array Nut -> Nut
h2_ = h2 []

h2__ :: String -> Nut
h2__ t = h2 [] [ DC.text_ t ]

instance TagToDeku "h3" (HTMLHeadingElement ())

h3 :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHeadingElement ()))) -> Array Nut -> Nut
h3 = elementify2 Nothing "h3"

h3_ :: Array Nut -> Nut
h3_ = h3 []

h3__ :: String -> Nut
h3__ t = h3 [] [ DC.text_ t ]

instance TagToDeku "h4" (HTMLHeadingElement ())

h4 :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHeadingElement ()))) -> Array Nut -> Nut
h4 = elementify2 Nothing "h4"

h4_ :: Array Nut -> Nut
h4_ = h4 []

h4__ :: String -> Nut
h4__ t = h4 [] [ DC.text_ t ]

instance TagToDeku "h5" (HTMLHeadingElement ())

h5 :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHeadingElement ()))) -> Array Nut -> Nut
h5 = elementify2 Nothing "h5"

h5_ :: Array Nut -> Nut
h5_ = h5 []

h5__ :: String -> Nut
h5__ t = h5 [] [ DC.text_ t ]

instance TagToDeku "h6" (HTMLHeadingElement ())

h6 :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHeadingElement ()))) -> Array Nut -> Nut
h6 = elementify2 Nothing "h6"

h6_ :: Array Nut -> Nut
h6_ = h6 []

h6__ :: String -> Nut
h6__ t = h6 [] [ DC.text_ t ]

instance TagToDeku "hgroup" (HTMLElement ())

hgroup :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
hgroup = elementify2 Nothing "hgroup"

hgroup_ :: Array Nut -> Nut
hgroup_ = hgroup []

hgroup__ :: String -> Nut
hgroup__ t = hgroup [] [ DC.text_ t ]

instance TagToDeku "header" (HTMLElement ())

header :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
header = elementify2 Nothing "header"

header_ :: Array Nut -> Nut
header_ = header []

header__ :: String -> Nut
header__ t = header [] [ DC.text_ t ]

instance TagToDeku "footer" (HTMLElement ())

footer :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
footer = elementify2 Nothing "footer"

footer_ :: Array Nut -> Nut
footer_ = footer []

footer__ :: String -> Nut
footer__ t = footer [] [ DC.text_ t ]

instance TagToDeku "address" (HTMLElement ())

address :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
address = elementify2 Nothing "address"

address_ :: Array Nut -> Nut
address_ = address []

address__ :: String -> Nut
address__ t = address [] [ DC.text_ t ]

instance TagToDeku "p" (HTMLParagraphElement ())

p :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLParagraphElement ()))) -> Array Nut -> Nut
p = elementify2 Nothing "p"

p_ :: Array Nut -> Nut
p_ = p []

p__ :: String -> Nut
p__ t = p [] [ DC.text_ t ]

instance TagToDeku "hr" (HTMLHRElement ())

hr :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLHRElement ()))) -> Array Nut -> Nut
hr = elementify2 Nothing "hr"

hr_ :: Array Nut -> Nut
hr_ = hr []

hr__ :: String -> Nut
hr__ t = hr [] [ DC.text_ t ]

instance TagToDeku "pre" (HTMLPreElement ())

pre :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLPreElement ()))) -> Array Nut -> Nut
pre = elementify2 Nothing "pre"

pre_ :: Array Nut -> Nut
pre_ = pre []

pre__ :: String -> Nut
pre__ t = pre [] [ DC.text_ t ]

instance TagToDeku "blockquote" (HTMLQuoteElement ())

blockquote
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLQuoteElement ()))) -> Array Nut -> Nut
blockquote = elementify2 Nothing "blockquote"

blockquote_ :: Array Nut -> Nut
blockquote_ = blockquote []

blockquote__ :: String -> Nut
blockquote__ t = blockquote [] [ DC.text_ t ]

instance TagToDeku "ol" (HTMLOListElement ())

ol :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLOListElement ()))) -> Array Nut -> Nut
ol = elementify2 Nothing "ol"

ol_ :: Array Nut -> Nut
ol_ = ol []

ol__ :: String -> Nut
ol__ t = ol [] [ DC.text_ t ]

instance TagToDeku "ul" (HTMLUListElement ())

ul :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUListElement ()))) -> Array Nut -> Nut
ul = elementify2 Nothing "ul"

ul_ :: Array Nut -> Nut
ul_ = ul []

ul__ :: String -> Nut
ul__ t = ul [] [ DC.text_ t ]

instance TagToDeku "menu" (HTMLMenuElement ())

menu :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLMenuElement ()))) -> Array Nut -> Nut
menu = elementify2 Nothing "menu"

menu_ :: Array Nut -> Nut
menu_ = menu []

menu__ :: String -> Nut
menu__ t = menu [] [ DC.text_ t ]

instance TagToDeku "li" (HTMLLIElement ())

li :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLLIElement ()))) -> Array Nut -> Nut
li = elementify2 Nothing "li"

li_ :: Array Nut -> Nut
li_ = li []

li__ :: String -> Nut
li__ t = li [] [ DC.text_ t ]

instance TagToDeku "dl" (HTMLDListElement ())

dl :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLDListElement ()))) -> Array Nut -> Nut
dl = elementify2 Nothing "dl"

dl_ :: Array Nut -> Nut
dl_ = dl []

dl__ :: String -> Nut
dl__ t = dl [] [ DC.text_ t ]

instance TagToDeku "dt" (HTMLElement ())

dt :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
dt = elementify2 Nothing "dt"

dt_ :: Array Nut -> Nut
dt_ = dt []

dt__ :: String -> Nut
dt__ t = dt [] [ DC.text_ t ]

instance TagToDeku "dd" (HTMLElement ())

dd :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
dd = elementify2 Nothing "dd"

dd_ :: Array Nut -> Nut
dd_ = dd []

dd__ :: String -> Nut
dd__ t = dd [] [ DC.text_ t ]

instance TagToDeku "figure" (HTMLElement ())

figure :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
figure = elementify2 Nothing "figure"

figure_ :: Array Nut -> Nut
figure_ = figure []

figure__ :: String -> Nut
figure__ t = figure [] [ DC.text_ t ]

instance TagToDeku "figcaption" (HTMLElement ())

figcaption :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
figcaption = elementify2 Nothing "figcaption"

figcaption_ :: Array Nut -> Nut
figcaption_ = figcaption []

figcaption__ :: String -> Nut
figcaption__ t = figcaption [] [ DC.text_ t ]

instance TagToDeku "main" (HTMLElement ())

main :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
main = elementify2 Nothing "main"

main_ :: Array Nut -> Nut
main_ = main []

main__ :: String -> Nut
main__ t = main [] [ DC.text_ t ]

instance TagToDeku "search" (HTMLElement ())

search :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
search = elementify2 Nothing "search"

search_ :: Array Nut -> Nut
search_ = search []

search__ :: String -> Nut
search__ t = search [] [ DC.text_ t ]

instance TagToDeku "div" (HTMLDivElement ())

div :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLDivElement ()))) -> Array Nut -> Nut
div = elementify2 Nothing "div"

div_ :: Array Nut -> Nut
div_ = div []

div__ :: String -> Nut
div__ t = div [] [ DC.text_ t ]

instance TagToDeku "a" (HTMLAnchorElement ())

a :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLAnchorElement ()))) -> Array Nut -> Nut
a = elementify2 Nothing "a"

a_ :: Array Nut -> Nut
a_ = a []

a__ :: String -> Nut
a__ t = a [] [ DC.text_ t ]

instance TagToDeku "em" (HTMLElement ())

em :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
em = elementify2 Nothing "em"

em_ :: Array Nut -> Nut
em_ = em []

em__ :: String -> Nut
em__ t = em [] [ DC.text_ t ]

instance TagToDeku "strong" (HTMLElement ())

strong :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
strong = elementify2 Nothing "strong"

strong_ :: Array Nut -> Nut
strong_ = strong []

strong__ :: String -> Nut
strong__ t = strong [] [ DC.text_ t ]

instance TagToDeku "small" (HTMLElement ())

small :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
small = elementify2 Nothing "small"

small_ :: Array Nut -> Nut
small_ = small []

small__ :: String -> Nut
small__ t = small [] [ DC.text_ t ]

instance TagToDeku "s" (HTMLElement ())

s :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
s = elementify2 Nothing "s"

s_ :: Array Nut -> Nut
s_ = s []

s__ :: String -> Nut
s__ t = s [] [ DC.text_ t ]

instance TagToDeku "cite" (HTMLElement ())

cite :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
cite = elementify2 Nothing "cite"

cite_ :: Array Nut -> Nut
cite_ = cite []

cite__ :: String -> Nut
cite__ t = cite [] [ DC.text_ t ]

instance TagToDeku "q" (HTMLQuoteElement ())

q :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLQuoteElement ()))) -> Array Nut -> Nut
q = elementify2 Nothing "q"

q_ :: Array Nut -> Nut
q_ = q []

q__ :: String -> Nut
q__ t = q [] [ DC.text_ t ]

instance TagToDeku "dfn" (HTMLElement ())

dfn :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
dfn = elementify2 Nothing "dfn"

dfn_ :: Array Nut -> Nut
dfn_ = dfn []

dfn__ :: String -> Nut
dfn__ t = dfn [] [ DC.text_ t ]

instance TagToDeku "abbr" (HTMLElement ())

abbr :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
abbr = elementify2 Nothing "abbr"

abbr_ :: Array Nut -> Nut
abbr_ = abbr []

abbr__ :: String -> Nut
abbr__ t = abbr [] [ DC.text_ t ]

instance TagToDeku "ruby" (HTMLElement ())

ruby :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
ruby = elementify2 Nothing "ruby"

ruby_ :: Array Nut -> Nut
ruby_ = ruby []

ruby__ :: String -> Nut
ruby__ t = ruby [] [ DC.text_ t ]

instance TagToDeku "rt" (HTMLElement ())

rt :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
rt = elementify2 Nothing "rt"

rt_ :: Array Nut -> Nut
rt_ = rt []

rt__ :: String -> Nut
rt__ t = rt [] [ DC.text_ t ]

instance TagToDeku "rp" (HTMLElement ())

rp :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
rp = elementify2 Nothing "rp"

rp_ :: Array Nut -> Nut
rp_ = rp []

rp__ :: String -> Nut
rp__ t = rp [] [ DC.text_ t ]

instance TagToDeku "data" (HTMLDataElement ())

xdata :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLDataElement ()))) -> Array Nut -> Nut
xdata = elementify2 Nothing "data"

xdata_ :: Array Nut -> Nut
xdata_ = xdata []

xdata__ :: String -> Nut
xdata__ t = xdata [] [ DC.text_ t ]

instance TagToDeku "time" (HTMLTimeElement ())

time :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTimeElement ()))) -> Array Nut -> Nut
time = elementify2 Nothing "time"

time_ :: Array Nut -> Nut
time_ = time []

time__ :: String -> Nut
time__ t = time [] [ DC.text_ t ]

instance TagToDeku "code" (HTMLElement ())

code :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
code = elementify2 Nothing "code"

code_ :: Array Nut -> Nut
code_ = code []

code__ :: String -> Nut
code__ t = code [] [ DC.text_ t ]

instance TagToDeku "var" (HTMLElement ())

var :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
var = elementify2 Nothing "var"

var_ :: Array Nut -> Nut
var_ = var []

var__ :: String -> Nut
var__ t = var [] [ DC.text_ t ]

instance TagToDeku "samp" (HTMLElement ())

samp :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
samp = elementify2 Nothing "samp"

samp_ :: Array Nut -> Nut
samp_ = samp []

samp__ :: String -> Nut
samp__ t = samp [] [ DC.text_ t ]

instance TagToDeku "kbd" (HTMLElement ())

kbd :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
kbd = elementify2 Nothing "kbd"

kbd_ :: Array Nut -> Nut
kbd_ = kbd []

kbd__ :: String -> Nut
kbd__ t = kbd [] [ DC.text_ t ]

instance TagToDeku "sub" (HTMLElement ())

sub :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
sub = elementify2 Nothing "sub"

sub_ :: Array Nut -> Nut
sub_ = sub []

sub__ :: String -> Nut
sub__ t = sub [] [ DC.text_ t ]

instance TagToDeku "sup" (HTMLElement ())

sup :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
sup = elementify2 Nothing "sup"

sup_ :: Array Nut -> Nut
sup_ = sup []

sup__ :: String -> Nut
sup__ t = sup [] [ DC.text_ t ]

instance TagToDeku "i" (HTMLElement ())

i :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
i = elementify2 Nothing "i"

i_ :: Array Nut -> Nut
i_ = i []

i__ :: String -> Nut
i__ t = i [] [ DC.text_ t ]

instance TagToDeku "b" (HTMLElement ())

b :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
b = elementify2 Nothing "b"

b_ :: Array Nut -> Nut
b_ = b []

b__ :: String -> Nut
b__ t = b [] [ DC.text_ t ]

instance TagToDeku "u" (HTMLElement ())

u :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
u = elementify2 Nothing "u"

u_ :: Array Nut -> Nut
u_ = u []

u__ :: String -> Nut
u__ t = u [] [ DC.text_ t ]

instance TagToDeku "mark" (HTMLElement ())

mark :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
mark = elementify2 Nothing "mark"

mark_ :: Array Nut -> Nut
mark_ = mark []

mark__ :: String -> Nut
mark__ t = mark [] [ DC.text_ t ]

instance TagToDeku "bdi" (HTMLElement ())

bdi :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
bdi = elementify2 Nothing "bdi"

bdi_ :: Array Nut -> Nut
bdi_ = bdi []

bdi__ :: String -> Nut
bdi__ t = bdi [] [ DC.text_ t ]

instance TagToDeku "bdo" (HTMLElement ())

bdo :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
bdo = elementify2 Nothing "bdo"

bdo_ :: Array Nut -> Nut
bdo_ = bdo []

bdo__ :: String -> Nut
bdo__ t = bdo [] [ DC.text_ t ]

instance TagToDeku "span" (HTMLSpanElement ())

span :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLSpanElement ()))) -> Array Nut -> Nut
span = elementify2 Nothing "span"

span_ :: Array Nut -> Nut
span_ = span []

span__ :: String -> Nut
span__ t = span [] [ DC.text_ t ]

instance TagToDeku "br" (HTMLBRElement ())

br :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLBRElement ()))) -> Array Nut -> Nut
br = elementify2 Nothing "br"

br_ :: Array Nut -> Nut
br_ = br []

br__ :: String -> Nut
br__ t = br [] [ DC.text_ t ]

instance TagToDeku "wbr" (HTMLElement ())

wbr :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
wbr = elementify2 Nothing "wbr"

wbr_ :: Array Nut -> Nut
wbr_ = wbr []

wbr__ :: String -> Nut
wbr__ t = wbr [] [ DC.text_ t ]

instance TagToDeku "ins" (HTMLModElement ())

ins :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLModElement ()))) -> Array Nut -> Nut
ins = elementify2 Nothing "ins"

ins_ :: Array Nut -> Nut
ins_ = ins []

ins__ :: String -> Nut
ins__ t = ins [] [ DC.text_ t ]

instance TagToDeku "del" (HTMLModElement ())

del :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLModElement ()))) -> Array Nut -> Nut
del = elementify2 Nothing "del"

del_ :: Array Nut -> Nut
del_ = del []

del__ :: String -> Nut
del__ t = del [] [ DC.text_ t ]

instance TagToDeku "picture" (HTMLPictureElement ())

picture
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLPictureElement ()))) -> Array Nut -> Nut
picture = elementify2 Nothing "picture"

picture_ :: Array Nut -> Nut
picture_ = picture []

picture__ :: String -> Nut
picture__ t = picture [] [ DC.text_ t ]

instance TagToDeku "source" (HTMLSourceElement ())

source
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLSourceElement ()))) -> Array Nut -> Nut
source = elementify2 Nothing "source"

source_ :: Array Nut -> Nut
source_ = source []

source__ :: String -> Nut
source__ t = source [] [ DC.text_ t ]

instance TagToDeku "img" (HTMLImageElement ())

img :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLImageElement ()))) -> Array Nut -> Nut
img = elementify2 Nothing "img"

img_ :: Array Nut -> Nut
img_ = img []

img__ :: String -> Nut
img__ t = img [] [ DC.text_ t ]

instance TagToDeku "iframe" (HTMLIFrameElement ())

iframe
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLIFrameElement ()))) -> Array Nut -> Nut
iframe = elementify2 Nothing "iframe"

iframe_ :: Array Nut -> Nut
iframe_ = iframe []

iframe__ :: String -> Nut
iframe__ t = iframe [] [ DC.text_ t ]

instance TagToDeku "embed" (HTMLEmbedElement ())

embed :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLEmbedElement ()))) -> Array Nut -> Nut
embed = elementify2 Nothing "embed"

embed_ :: Array Nut -> Nut
embed_ = embed []

embed__ :: String -> Nut
embed__ t = embed [] [ DC.text_ t ]

instance TagToDeku "object" (HTMLObjectElement ())

object
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLObjectElement ()))) -> Array Nut -> Nut
object = elementify2 Nothing "object"

object_ :: Array Nut -> Nut
object_ = object []

object__ :: String -> Nut
object__ t = object [] [ DC.text_ t ]

instance TagToDeku "video" (HTMLVideoElement ())

video :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLVideoElement ()))) -> Array Nut -> Nut
video = elementify2 Nothing "video"

video_ :: Array Nut -> Nut
video_ = video []

video__ :: String -> Nut
video__ t = video [] [ DC.text_ t ]

instance TagToDeku "audio" (HTMLAudioElement ())

audio :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLAudioElement ()))) -> Array Nut -> Nut
audio = elementify2 Nothing "audio"

audio_ :: Array Nut -> Nut
audio_ = audio []

audio__ :: String -> Nut
audio__ t = audio [] [ DC.text_ t ]

instance TagToDeku "track" (HTMLTrackElement ())

track :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTrackElement ()))) -> Array Nut -> Nut
track = elementify2 Nothing "track"

track_ :: Array Nut -> Nut
track_ = track []

track__ :: String -> Nut
track__ t = track [] [ DC.text_ t ]

instance TagToDeku "map" (HTMLMapElement ())

map :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLMapElement ()))) -> Array Nut -> Nut
map = elementify2 Nothing "map"

map_ :: Array Nut -> Nut
map_ = map []

map__ :: String -> Nut
map__ t = map [] [ DC.text_ t ]

instance TagToDeku "area" (HTMLAreaElement ())

area :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLAreaElement ()))) -> Array Nut -> Nut
area = elementify2 Nothing "area"

area_ :: Array Nut -> Nut
area_ = area []

area__ :: String -> Nut
area__ t = area [] [ DC.text_ t ]

instance TagToDeku "table" (HTMLTableElement ())

table :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableElement ()))) -> Array Nut -> Nut
table = elementify2 Nothing "table"

table_ :: Array Nut -> Nut
table_ = table []

table__ :: String -> Nut
table__ t = table [] [ DC.text_ t ]

instance TagToDeku "caption" (HTMLTableCaptionElement ())

caption
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableCaptionElement ())))
  -> Array Nut
  -> Nut
caption = elementify2 Nothing "caption"

caption_ :: Array Nut -> Nut
caption_ = caption []

caption__ :: String -> Nut
caption__ t = caption [] [ DC.text_ t ]

instance TagToDeku "colgroup" (HTMLTableColElement ())

colgroup
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableColElement ()))) -> Array Nut -> Nut
colgroup = elementify2 Nothing "colgroup"

colgroup_ :: Array Nut -> Nut
colgroup_ = colgroup []

colgroup__ :: String -> Nut
colgroup__ t = colgroup [] [ DC.text_ t ]

instance TagToDeku "col" (HTMLTableColElement ())

col
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableColElement ()))) -> Array Nut -> Nut
col = elementify2 Nothing "col"

col_ :: Array Nut -> Nut
col_ = col []

col__ :: String -> Nut
col__ t = col [] [ DC.text_ t ]

instance TagToDeku "tbody" (HTMLTableSectionElement ())

tbody
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableSectionElement ())))
  -> Array Nut
  -> Nut
tbody = elementify2 Nothing "tbody"

tbody_ :: Array Nut -> Nut
tbody_ = tbody []

tbody__ :: String -> Nut
tbody__ t = tbody [] [ DC.text_ t ]

instance TagToDeku "thead" (HTMLTableSectionElement ())

thead
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableSectionElement ())))
  -> Array Nut
  -> Nut
thead = elementify2 Nothing "thead"

thead_ :: Array Nut -> Nut
thead_ = thead []

thead__ :: String -> Nut
thead__ t = thead [] [ DC.text_ t ]

instance TagToDeku "tfoot" (HTMLTableSectionElement ())

tfoot
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableSectionElement ())))
  -> Array Nut
  -> Nut
tfoot = elementify2 Nothing "tfoot"

tfoot_ :: Array Nut -> Nut
tfoot_ = tfoot []

tfoot__ :: String -> Nut
tfoot__ t = tfoot [] [ DC.text_ t ]

instance TagToDeku "tr" (HTMLTableRowElement ())

tr :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableRowElement ()))) -> Array Nut -> Nut
tr = elementify2 Nothing "tr"

tr_ :: Array Nut -> Nut
tr_ = tr []

tr__ :: String -> Nut
tr__ t = tr [] [ DC.text_ t ]

instance TagToDeku "td" (HTMLTableCellElement ())

td
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableCellElement ()))) -> Array Nut -> Nut
td = elementify2 Nothing "td"

td_ :: Array Nut -> Nut
td_ = td []

td__ :: String -> Nut
td__ t = td [] [ DC.text_ t ]

instance TagToDeku "th" (HTMLTableCellElement ())

th
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTableCellElement ()))) -> Array Nut -> Nut
th = elementify2 Nothing "th"

th_ :: Array Nut -> Nut
th_ = th []

th__ :: String -> Nut
th__ t = th [] [ DC.text_ t ]

instance TagToDeku "form" (HTMLFormElement ())

form :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLFormElement ()))) -> Array Nut -> Nut
form = elementify2 Nothing "form"

form_ :: Array Nut -> Nut
form_ = form []

form__ :: String -> Nut
form__ t = form [] [ DC.text_ t ]

instance TagToDeku "label" (HTMLLabelElement ())

label :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLLabelElement ()))) -> Array Nut -> Nut
label = elementify2 Nothing "label"

label_ :: Array Nut -> Nut
label_ = label []

label__ :: String -> Nut
label__ t = label [] [ DC.text_ t ]

instance TagToDeku "input" (HTMLInputElement ())

input :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLInputElement ()))) -> Array Nut -> Nut
input = elementify2 Nothing "input"

input_ :: Array Nut -> Nut
input_ = input []

input__ :: String -> Nut
input__ t = input [] [ DC.text_ t ]

instance TagToDeku "button" (HTMLButtonElement ())

button
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLButtonElement ()))) -> Array Nut -> Nut
button = elementify2 Nothing "button"

button_ :: Array Nut -> Nut
button_ = button []

button__ :: String -> Nut
button__ t = button [] [ DC.text_ t ]

instance TagToDeku "select" (HTMLSelectElement ())

select
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLSelectElement ()))) -> Array Nut -> Nut
select = elementify2 Nothing "select"

select_ :: Array Nut -> Nut
select_ = select []

select__ :: String -> Nut
select__ t = select [] [ DC.text_ t ]

instance TagToDeku "datalist" (HTMLDataListElement ())

datalist
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLDataListElement ()))) -> Array Nut -> Nut
datalist = elementify2 Nothing "datalist"

datalist_ :: Array Nut -> Nut
datalist_ = datalist []

datalist__ :: String -> Nut
datalist__ t = datalist [] [ DC.text_ t ]

instance TagToDeku "optgroup" (HTMLOptGroupElement ())

optgroup
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLOptGroupElement ()))) -> Array Nut -> Nut
optgroup = elementify2 Nothing "optgroup"

optgroup_ :: Array Nut -> Nut
optgroup_ = optgroup []

optgroup__ :: String -> Nut
optgroup__ t = optgroup [] [ DC.text_ t ]

instance TagToDeku "option" (HTMLOptionElement ())

option
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLOptionElement ()))) -> Array Nut -> Nut
option = elementify2 Nothing "option"

option_ :: Array Nut -> Nut
option_ = option []

option__ :: String -> Nut
option__ t = option [] [ DC.text_ t ]

instance TagToDeku "textarea" (HTMLTextAreaElement ())

textarea
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTextAreaElement ()))) -> Array Nut -> Nut
textarea = elementify2 Nothing "textarea"

textarea_ :: Array Nut -> Nut
textarea_ = textarea []

textarea__ :: String -> Nut
textarea__ t = textarea [] [ DC.text_ t ]

instance TagToDeku "output" (HTMLOutputElement ())

output
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLOutputElement ()))) -> Array Nut -> Nut
output = elementify2 Nothing "output"

output_ :: Array Nut -> Nut
output_ = output []

output__ :: String -> Nut
output__ t = output [] [ DC.text_ t ]

instance TagToDeku "progress" (HTMLProgressElement ())

progress
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLProgressElement ()))) -> Array Nut -> Nut
progress = elementify2 Nothing "progress"

progress_ :: Array Nut -> Nut
progress_ = progress []

progress__ :: String -> Nut
progress__ t = progress [] [ DC.text_ t ]

instance TagToDeku "meter" (HTMLMeterElement ())

meter :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLMeterElement ()))) -> Array Nut -> Nut
meter = elementify2 Nothing "meter"

meter_ :: Array Nut -> Nut
meter_ = meter []

meter__ :: String -> Nut
meter__ t = meter [] [ DC.text_ t ]

instance TagToDeku "fieldset" (HTMLFieldSetElement ())

fieldset
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLFieldSetElement ()))) -> Array Nut -> Nut
fieldset = elementify2 Nothing "fieldset"

fieldset_ :: Array Nut -> Nut
fieldset_ = fieldset []

fieldset__ :: String -> Nut
fieldset__ t = fieldset [] [ DC.text_ t ]

instance TagToDeku "legend" (HTMLLegendElement ())

legend
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLLegendElement ()))) -> Array Nut -> Nut
legend = elementify2 Nothing "legend"

legend_ :: Array Nut -> Nut
legend_ = legend []

legend__ :: String -> Nut
legend__ t = legend [] [ DC.text_ t ]

instance TagToDeku "details" (HTMLDetailsElement ())

details
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLDetailsElement ()))) -> Array Nut -> Nut
details = elementify2 Nothing "details"

details_ :: Array Nut -> Nut
details_ = details []

details__ :: String -> Nut
details__ t = details [] [ DC.text_ t ]

instance TagToDeku "summary" (HTMLElement ())

summary :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
summary = elementify2 Nothing "summary"

summary_ :: Array Nut -> Nut
summary_ = summary []

summary__ :: String -> Nut
summary__ t = summary [] [ DC.text_ t ]

instance TagToDeku "dialog" (HTMLDialogElement ())

dialog
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLDialogElement ()))) -> Array Nut -> Nut
dialog = elementify2 Nothing "dialog"

dialog_ :: Array Nut -> Nut
dialog_ = dialog []

dialog__ :: String -> Nut
dialog__ t = dialog [] [ DC.text_ t ]

instance TagToDeku "script" (HTMLScriptElement ())

script
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLScriptElement ()))) -> Array Nut -> Nut
script = elementify2 Nothing "script"

script_ :: Array Nut -> Nut
script_ = script []

script__ :: String -> Nut
script__ t = script [] [ DC.text_ t ]

instance TagToDeku "noscript" (HTMLElement ())

noscript :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
noscript = elementify2 Nothing "noscript"

noscript_ :: Array Nut -> Nut
noscript_ = noscript []

noscript__ :: String -> Nut
noscript__ t = noscript [] [ DC.text_ t ]

instance TagToDeku "template" (HTMLTemplateElement ())

template
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLTemplateElement ()))) -> Array Nut -> Nut
template = elementify2 Nothing "template"

template_ :: Array Nut -> Nut
template_ = template []

template__ :: String -> Nut
template__ t = template [] [ DC.text_ t ]

instance TagToDeku "slot" (HTMLSlotElement ())

slot :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLSlotElement ()))) -> Array Nut -> Nut
slot = elementify2 Nothing "slot"

slot_ :: Array Nut -> Nut
slot_ = slot []

slot__ :: String -> Nut
slot__ t = slot [] [ DC.text_ t ]

instance TagToDeku "canvas" (HTMLCanvasElement ())

canvas
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLCanvasElement ()))) -> Array Nut -> Nut
canvas = elementify2 Nothing "canvas"

canvas_ :: Array Nut -> Nut
canvas_ = canvas []

canvas__ :: String -> Nut
canvas__ t = canvas [] [ DC.text_ t ]

instance TagToDeku "applet" (HTMLUnknownElement ())

applet
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
applet = elementify2 Nothing "applet"

applet_ :: Array Nut -> Nut
applet_ = applet []

applet__ :: String -> Nut
applet__ t = applet [] [ DC.text_ t ]

instance TagToDeku "acronym" (HTMLElement ())

acronym :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
acronym = elementify2 Nothing "acronym"

acronym_ :: Array Nut -> Nut
acronym_ = acronym []

acronym__ :: String -> Nut
acronym__ t = acronym [] [ DC.text_ t ]

instance TagToDeku "bgsound" (HTMLUnknownElement ())

bgsound
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
bgsound = elementify2 Nothing "bgsound"

bgsound_ :: Array Nut -> Nut
bgsound_ = bgsound []

bgsound__ :: String -> Nut
bgsound__ t = bgsound [] [ DC.text_ t ]

instance TagToDeku "dir" (HTMLDirectoryElement ())

dir
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLDirectoryElement ()))) -> Array Nut -> Nut
dir = elementify2 Nothing "dir"

dir_ :: Array Nut -> Nut
dir_ = dir []

dir__ :: String -> Nut
dir__ t = dir [] [ DC.text_ t ]

instance TagToDeku "frame" (HTMLFrameElement ())

frame :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLFrameElement ()))) -> Array Nut -> Nut
frame = elementify2 Nothing "frame"

frame_ :: Array Nut -> Nut
frame_ = frame []

frame__ :: String -> Nut
frame__ t = frame [] [ DC.text_ t ]

instance TagToDeku "frameset" (HTMLFrameSetElement ())

frameset
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLFrameSetElement ()))) -> Array Nut -> Nut
frameset = elementify2 Nothing "frameset"

frameset_ :: Array Nut -> Nut
frameset_ = frameset []

frameset__ :: String -> Nut
frameset__ t = frameset [] [ DC.text_ t ]

instance TagToDeku "noframes" (HTMLElement ())

noframes :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
noframes = elementify2 Nothing "noframes"

noframes_ :: Array Nut -> Nut
noframes_ = noframes []

noframes__ :: String -> Nut
noframes__ t = noframes [] [ DC.text_ t ]

instance TagToDeku "isindex" (HTMLUnknownElement ())

isindex
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
isindex = elementify2 Nothing "isindex"

isindex_ :: Array Nut -> Nut
isindex_ = isindex []

isindex__ :: String -> Nut
isindex__ t = isindex [] [ DC.text_ t ]

instance TagToDeku "keygen" (HTMLUnknownElement ())

keygen
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
keygen = elementify2 Nothing "keygen"

keygen_ :: Array Nut -> Nut
keygen_ = keygen []

keygen__ :: String -> Nut
keygen__ t = keygen [] [ DC.text_ t ]

instance TagToDeku "listing" (HTMLPreElement ())

listing :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLPreElement ()))) -> Array Nut -> Nut
listing = elementify2 Nothing "listing"

listing_ :: Array Nut -> Nut
listing_ = listing []

listing__ :: String -> Nut
listing__ t = listing [] [ DC.text_ t ]

instance TagToDeku "menuitem" (HTMLElement ())

menuitem :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
menuitem = elementify2 Nothing "menuitem"

menuitem_ :: Array Nut -> Nut
menuitem_ = menuitem []

menuitem__ :: String -> Nut
menuitem__ t = menuitem [] [ DC.text_ t ]

instance TagToDeku "nextid" (HTMLUnknownElement ())

nextid
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
nextid = elementify2 Nothing "nextid"

nextid_ :: Array Nut -> Nut
nextid_ = nextid []

nextid__ :: String -> Nut
nextid__ t = nextid [] [ DC.text_ t ]

instance TagToDeku "noembed" (HTMLElement ())

noembed :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
noembed = elementify2 Nothing "noembed"

noembed_ :: Array Nut -> Nut
noembed_ = noembed []

noembed__ :: String -> Nut
noembed__ t = noembed [] [ DC.text_ t ]

instance TagToDeku "param" (HTMLParamElement ())

param :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLParamElement ()))) -> Array Nut -> Nut
param = elementify2 Nothing "param"

param_ :: Array Nut -> Nut
param_ = param []

param__ :: String -> Nut
param__ t = param [] [ DC.text_ t ]

instance TagToDeku "plaintext" (HTMLElement ())

plaintext :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
plaintext = elementify2 Nothing "plaintext"

plaintext_ :: Array Nut -> Nut
plaintext_ = plaintext []

plaintext__ :: String -> Nut
plaintext__ t = plaintext [] [ DC.text_ t ]

instance TagToDeku "rb" (HTMLElement ())

rb :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
rb = elementify2 Nothing "rb"

rb_ :: Array Nut -> Nut
rb_ = rb []

rb__ :: String -> Nut
rb__ t = rb [] [ DC.text_ t ]

instance TagToDeku "rtc" (HTMLElement ())

rtc :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
rtc = elementify2 Nothing "rtc"

rtc_ :: Array Nut -> Nut
rtc_ = rtc []

rtc__ :: String -> Nut
rtc__ t = rtc [] [ DC.text_ t ]

instance TagToDeku "strike" (HTMLElement ())

strike :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
strike = elementify2 Nothing "strike"

strike_ :: Array Nut -> Nut
strike_ = strike []

strike__ :: String -> Nut
strike__ t = strike [] [ DC.text_ t ]

instance TagToDeku "xmp" (HTMLPreElement ())

xmp :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLPreElement ()))) -> Array Nut -> Nut
xmp = elementify2 Nothing "xmp"

xmp_ :: Array Nut -> Nut
xmp_ = xmp []

xmp__ :: String -> Nut
xmp__ t = xmp [] [ DC.text_ t ]

instance TagToDeku "basefont" (HTMLElement ())

basefont :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
basefont = elementify2 Nothing "basefont"

basefont_ :: Array Nut -> Nut
basefont_ = basefont []

basefont__ :: String -> Nut
basefont__ t = basefont [] [ DC.text_ t ]

instance TagToDeku "big" (HTMLElement ())

big :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
big = elementify2 Nothing "big"

big_ :: Array Nut -> Nut
big_ = big []

big__ :: String -> Nut
big__ t = big [] [ DC.text_ t ]

instance TagToDeku "blink" (HTMLUnknownElement ())

blink
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
blink = elementify2 Nothing "blink"

blink_ :: Array Nut -> Nut
blink_ = blink []

blink__ :: String -> Nut
blink__ t = blink [] [ DC.text_ t ]

instance TagToDeku "center" (HTMLElement ())

center :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
center = elementify2 Nothing "center"

center_ :: Array Nut -> Nut
center_ = center []

center__ :: String -> Nut
center__ t = center [] [ DC.text_ t ]

instance TagToDeku "font" (HTMLFontElement ())

font :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLFontElement ()))) -> Array Nut -> Nut
font = elementify2 Nothing "font"

font_ :: Array Nut -> Nut
font_ = font []

font__ :: String -> Nut
font__ t = font [] [ DC.text_ t ]

instance TagToDeku "marquee" (HTMLMarqueeElement ())

marquee
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLMarqueeElement ()))) -> Array Nut -> Nut
marquee = elementify2 Nothing "marquee"

marquee_ :: Array Nut -> Nut
marquee_ = marquee []

marquee__ :: String -> Nut
marquee__ t = marquee [] [ DC.text_ t ]

instance TagToDeku "multicol" (HTMLUnknownElement ())

multicol
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
multicol = elementify2 Nothing "multicol"

multicol_ :: Array Nut -> Nut
multicol_ = multicol []

multicol__ :: String -> Nut
multicol__ t = multicol [] [ DC.text_ t ]

instance TagToDeku "nobr" (HTMLElement ())

nobr :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
nobr = elementify2 Nothing "nobr"

nobr_ :: Array Nut -> Nut
nobr_ = nobr []

nobr__ :: String -> Nut
nobr__ t = nobr [] [ DC.text_ t ]

instance TagToDeku "spacer" (HTMLUnknownElement ())

spacer
  :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLUnknownElement ()))) -> Array Nut -> Nut
spacer = elementify2 Nothing "spacer"

spacer_ :: Array Nut -> Nut
spacer_ = spacer []

spacer__ :: String -> Nut
spacer__ t = spacer [] [ DC.text_ t ]

instance TagToDeku "tt" (HTMLElement ())

tt :: Array (FRP.Poll.Poll (Deku.Attribute.Attribute (HTMLElement ()))) -> Array Nut -> Nut
tt = elementify2 Nothing "tt"

tt_ :: Array Nut -> Nut
tt_ = tt []

tt__ :: String -> Nut
tt__ t = tt [] [ DC.text_ t ]
