{ name = "purescript-deku"
, dependencies =
  [ "avar"
  , "control"
  , "effect"
  , "either"
  , "event"
  , "exceptions"
  , "fast-vect"
  , "filterable"
  , "foldable-traversable"
  , "foreign-object"
  , "maybe"
  , "newtype"
  , "prelude"
  , "profunctor"
  , "random"
  , "record"
  , "refs"
  , "safe-coerce"
  , "tuples"
  , "type-equality"
  , "unsafe-coerce"
  , "web-dom"
  , "web-events"
  , "web-html"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs" ]
}
